package net.gsantner.markor.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 Seed Color
val Seed = Color(0xFF0061A4)

// Light Palette - Complete M3 Color Roles
val md_theme_light_primary = Color(0xFF005AC1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
val md_theme_light_secondary = Color(0xFF535E78)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF0F1B32)
val md_theme_light_tertiary = Color(0xFF76517B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFED7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2D0E34)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF5F3F7)
val md_theme_light_surfaceContainer = Color(0xFFEFEDF1)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9E7EC)
val md_theme_light_surfaceContainerHighest = Color(0xFFE4E2E6)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Palette - Complete M3 Color Roles
val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF004494)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFBBC7E4)
val md_theme_dark_onSecondary = Color(0xFF253048)
val md_theme_dark_secondaryContainer = Color(0xFF3B475F)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_tertiary = Color(0xFFE5B9EA)
val md_theme_dark_onTertiary = Color(0xFF44244A)
val md_theme_dark_tertiaryContainer = Color(0xFF5D3A62)
val md_theme_dark_onTertiaryContainer = Color(0xFFFED7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0E0E11)
val md_theme_dark_surfaceContainerLow = Color(0xFF1B1B1F)
val md_theme_dark_surfaceContainer = Color(0xFF1F1F23)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2A2A2E)
val md_theme_dark_surfaceContainerHighest = Color(0xFF353539)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inverseOnSurface = Color(0xFF303034)
val md_theme_dark_inversePrimary = Color(0xFF005AC1)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_scrim = Color(0xFF000000)

// Markor Specifics (Editor & Accents)
val EditorBackgroundLight = Color(0xFFFFFFFF)
val EditorBackgroundDark = Color(0xFF0A0B0F)
val SuccessGreen = Color(0xFF2E7D32)
val WarningOrange = Color(0xFFED6C02)
